### ISSUE TITLE
error with the BSmooth

### ISSUE THREAD

**Issue by HYan-lei** [hansenlab/bsseq#101]
I got the following wrong message when i run BSmooth, can anyone please give me some suggestions? Thanks.

```r
[read.bismark] Constructing BSseq object ...
Error in result[[njob]] <- value :
  attempt to select less than one element in OneIndex
Calls: BSmooth ... doTryCatch -> bplapply -> bplapply -> bploop -> bploop.lapply
In addition: Warning message:
In parallel::mccollect(wait = FALSE, timeout = 1) :
  2 parallel jobs did not deliver results
Execution halted
```

Here is my script,

```r
t1 <- read.bismark(files="1_MDB1449.dd.bismark.cov.gz", loci=NULL, colData = DataFrame(row.names = "t1"), rmZeroCov = FALSE,verbose = TRUE)
t11 <- read.bismark(files="11_MDB181.dd.bismark.cov.gz", loci=NULL, colData = DataFrame(row.names = "t11"), rmZeroCov = FALSE,verbose = TRUE)
BSseq <- combineList(list(t1,t11), BACKEND=NULL)
BSseq.1 <- BSmooth(BSseq, verbose = TRUE)
```

**Comment by PeteHaitch** [comment]
Can you please share the output of `BiocManager::valid()`.
Is it possible to share the `BSseq.1` object (via Dropbox or similar)?

**Comment by HYan-lei** [comment]
Thanks. Can you tell me how to save the BSseq.1 object? or I can share the .cov.gz file with you through Box?

here is the BiocManager::valid() output,

* sessionInfo()

R version 4.0.5 (2021-03-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/local/intel/compilers_and_libraries_2020.2.254/linux/mkl/lib/intel64_lin/libmkl_rt.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] BiocManager_1.30.15 compiler_4.0.5      tools_4.0.5

Bioconductor version '3.12'

  * 60 packages out-of-date
  * 0 packages too new

create a valid installation with

  BiocManager::install(c(
    "Amelia", "biclust", "BMA", "bslib", "cachem", "caret", "ClusterR",
    "DeconRNASeq", "DEoptimR", "distillery", "e1071", "effectsize", "extRemes",
    "fansi", "fastcluster", "fdapace", "fields", "formatR", "h2o", "hms",
    "htmlTable", "inline", "ks", "leiden", "lme4", "MatchIt", "mixmeta",
    "mvnfast", "numbers", "opencv", "OpenImageR", "optmatch", "performance",
    "pillar", "plot3D", "plot3Drgl", "RcppArmadillo", "readstata13", "Rfast",
    "rJava", "RNifti", "rnoaa", "rsconnect", "rversions", "sandwich", "Seurat",
    "shape", "signal", "sjPlot", "solrium", "spdep", "stringi", "systemfonts",
    "textshaping", "tibble", "timereg", "V8", "WikidataR", "xaringan", "xfun"
  ), update = TRUE, ask = FALSE)

more details: BiocManager::valid()$too_new, BiocManager::valid()$out_of_date

**Comment by PeteHaitch** [comment]
Would you please first try following the advice from `BiocManager::install()` and update the out-of-date packages. I don't see any obvious candidates amongst those that might be causing problems, but it'd be good to first rule that out.
Sure, you can share the `.cov.gz` files if that's easier.

**Comment by PeteHaitch** [comment]
I'm going to close this for now, but please re-open if you are able to share the example files.

**Comment by HYan-lei** [comment]
Hi,

Can you try whether you can download from this link,
https://nih.box.com/s/ynjtna2wl841clmyoigjterbon528wz2? Thanks.

HY

**Comment by PeteHaitch** [comment]
No, it doesn't work for me (after creating a Box account).
I get the error:

> This shared file or folder link has been removed or is unavailable to you.

**Comment by HYan-lei** [comment]
Can you please tell me your email address? I may need to share with you
first. Thanks.

**Comment by PeteHaitch** [comment]
https://github.com/hansenlab/bsseq/blob/1aa857c0977b21f3621f451420ff030c39d91afd/DESCRIPTION#L9

**Comment by PeteHaitch** [comment]
thanks, downloading now

**Comment by PeteHaitch** [comment]
I think what is happening is that you are running out of memory.
Unfortunately, that error is not being propagated to you and you receive the mysterious error message^[1].
How much RAM do you have available?

I'm currently testing this theory by running the below code on a server and I'll let you know the outcome.

```r
library(bsseq)

# NOTE: You can read in all the files in a single call to read.bismar(). 
#       This should be more efficient than reading each file in and then running combineList().
bsseq <- read.bismark(
  # NOTE: The file in the original bug report is named 1_MDB1449.dd.bismark.cov.gz
  files = c("060721/10_MDB1425.dd.bismark.cov.gz", "060721/11_MDB181.dd.bismark.cov.gz"),
  loci=NULL,
  colData = DataFrame(row.names = c("t10", "t11")),
  rmZeroCov = FALSE,
  verbose = TRUE)

# NOTE: Running on the first 100,000 loci worked fine for me.
# NOTE: I am using serial processing to simplify things for myself.
bsseq_subset <- BSmooth(bsseq[1:100000, ], verbose = TRUE, BPPARAM = BiocParallel::SerialParam())

bsseq <- BSmooth(bsseq, verbose = TRUE, BPPARAM = BiocParallel::SerialParam())
```

^[1]: Note to self, the error message being masked occurs when `smooth` is an error message but `bpok(smooth)` 'doesn't detect' this (this is perhaps changed behaviour); reported https://github.com/Bioconductor/BiocParallel/issues/142 (although may not be cause of the issue reported by @HYan-lei)

**Comment by orca118** [comment]
I tried different memory and even failed with 3000g memory. Thanks.

HY

**Comment by PeteHaitch** [comment]
I was able to smooth the example data you sent me (as described in https://github.com/hansenlab/bsseq/issues/101#issuecomment-858327882), so I'm having a hard time reproducing the problem.
Did you try what I [recommended earlier](https://github.com/hansenlab/bsseq/issues/101#issuecomment-849214614):

> Would you please first try following the advice from `BiocManager::install()` and update the out-of-date packages. I don't see any obvious candidates amongst those that might be causing problems, but it'd be good to first rule that out.

I noted that one of the files you sent me does not have the same name as that in your original bug report. Could it be something specific to that file?

**Comment by orca118** [comment]
Hi, Peter:

Thanks for your great help. How long do you take and how much memory do you
use? Does bsseq need to run on R 4.1? Our R is 4.0.5. I reinstalled the
bsseq, but i could not update all the packages. I will ask our system
administrator to update the R first. I have several files that need to run,
and the input files should be no problem. Thanks.

HY

**Comment by PeteHaitch** [comment]
I re-ran it successfully on R 4.0.5 using `BSseq <- BSmooth(BSseq, verbose = TRUE, BPPARAM = BiocParallel::SerialParam())`
It took ~12 hours on a machine I reserved with 1 core and 64 GB of RAM.
I'm didn't track memory usage, so I'm unsure how much of that 64 GB was required.

If you're finding that you are unable to smooth all samples at once, one pragmatic solution is to smooth each sample separately, save each, then `cbind()` these and save the combined object.
The only caveat is to make sure you first construct the set of 'valid loci' across all samples. 
You can identify the 'valid loci' using this piece of code (this is the code used internally by `read.bismark()` when the loci aren't supplied i.e. when `loci = NULL`):

```r
loci <- bsseq:::.contructFWGRangesFromBismarkFiles(files = files, 
            rmZeroCov = rmZeroCov, strandCollapse = strandCollapse, 
            verbose = subverbose, nThread = nThread, BPPARAM = BPPARAM)
```

**Comment by orca118** [comment]
Hi, Peter:

I  can run successfully now on R 4.0.5 with BSseq <- BSmooth(BSseq, verbose
= TRUE, BPPARAM = BiocParallel::SerialParam()); It took a long time for me
and used a lot memory. But finally it worked. Thanks so much for your great
help.

Jobid        Partition       State  Nodes  CPUs      Walltime       Runtime
        MemReq  MemUsed  Nodelist
16876281      largemem   COMPLETED      1     2    4-00:00:00      19:50:15
 3000.0GB/node  605.2GB  cn4266

best

HY

**Comment by PeteHaitch** [comment]
Glad to hear! I'm not currently actively developing **bsseq** but next time I am I will see what might improve the performance.
