### ISSUE TITLE
BSmooth error

### ISSUE THREAD

**Issue by kir1to455** [hansenlab/bsseq#107]
Hi，
When I Use BSmooth algorithm for estimating methylation levels, I encountered some problems:

![image](https://user-images.githubusercontent.com/87375686/151657756-1bcb595e-1441-4c12-b92f-8d09a428fce7.png)

I used the following code for reading my files and then performing the BSmooth.

![image](https://user-images.githubusercontent.com/87375686/151657855-430fbf3d-d702-44b9-9196-464def1fe477.png)

Could you give some advice?

Thank you so much for your help.
JiaLiang He

**Comment by kir1to455** [comment]
BSobj_chr21
![image](https://user-images.githubusercontent.com/87375686/151658045-71ac0788-c8ae-4ce7-9c44-318a490781d7.png)

**Comment by PeteHaitch** [comment]
See https://github.com/hansenlab/bsseq/issues/104#issuecomment-1034365408
