### ISSUE TITLE
Is it possible to append metadata to the GRanges within BSseq objects?

### ISSUE THREAD

**Issue by lukesarre** [hansenlab/bsseq#112]
Hello, 

Thank you very much for developing bsseq, it has been an incredibly useful tool in my research.

I would like to append metadata to the GRanges part of the BSseq object.
For example I would like rows to contain their dinucleotide context ("CA", "CT", etc.)

I have tried methods such as:
`granges(bs)$metadata = c("CA", "CT"`)
and
`values(granges(bs)) = DataFrame(metadata = c("CA", "CT"))`

However, both methods give the error:
`could not find function "granges<-"`

Is it that BSseq objects are restricted from containing metadata? Or perhaps I am missing something more obvious?

Many thanks for your help, and I appreciate the work you have put into this package.
Luke

**Comment by PeteHaitch** [comment]
I think you want `rowRanges(bs)`, e.g., if your _BSseq_ object contains 2 loci and you wanted to add the context you could do `rowRanges(bs)$context <- c("CA", "CT")`

**Comment by PeteHaitch** [comment]
FYI Formally, a _BSseq_ object is a _SummarizedExperiment_ object, so the syntax is the same.
If you're not familiar with interacting with _SummarizedExperiment_ objects, then the vignette may help (https://bioconductor.org/packages/release/bioc/vignettes/SummarizedExperiment/inst/doc/SummarizedExperiment.html)

**Comment by lukesarre** [comment]
That did the trick, perfect. And the vignette was very helpful
Thank you for your help,
Luke
