### ISSUE TITLE
read.bismark: option to change tmpdir in fread?

### ISSUE THREAD

**Issue by jarbet** [hansenlab/bsseq#117]
I see that `read.bismark` calls `fread` which uses a temporary directory specified by the `tmpdir` argument.  

However, I don't have permission to write to the default temporary directory `tmpdir=tempdir()`, so I get this error:

> Error: No write permission for directory: /tmp/RtmpMHx4NI

Would it be possible to give the user the option to change the `tmpdir`, that way I can change it to use a directory I have write permissions in?

**Comment by PeteHaitch** [comment]
I think the location of `tempdir()` can be controlled by environment variables.
From `?tempdir`:

> The environment variables `TMPDIR`, `TMP` and `TEMP` are checked in turn and the first found which points to a writable directory is used: if none succeeds ‘`/tmp`’ is used. The path should not contain spaces. **Note that setting any of these environment variables in the R session has no effect on `tempdir()`: the per-session temporary directory is created before the interpreter is started.** [emphasis mine]

This means that you need to set this environment variable before starting R.
From memory, this is done using a `.Renviron` file, which can be at the user or project-level (https://support.posit.co/hc/en-us/articles/360047157094-Managing-R-with-Rprofile-Renviron-Rprofile-site-Renviron-site-rsession-conf-and-repos-conf).

**Comment by PeteHaitch** [comment]
If you do it this way, all R code you run that uses `tempdir()` will benefit (not just `data.table::fread()` and in turn `bsseq::read.bismark()`).
I am unlikely to add a `tmpdir` argument to `bsseq::read.bismar()` unless this proposed solution doesn't work (I don't have time to test myself just now, but I seem to recall making use of it in the past).

**Comment by jarbet** [comment]
> If you do it this way, all R code you run that uses `tempdir()` will benefit (not just `data.table::fread()` and in turn `bsseq::read.bismark()`). I am unlikely to add a `tmpdir` argument to `bsseq::read.bismar()` unless this proposed solution doesn't work (I don't have time to test myself just now, but I seem to recall making use of it in the past).

Changing the `TMPDIR` environment variable solved this issue.  Thanks!

**Comment by PeteHaitch** [comment]
Great, happy to help.
