### ISSUE TITLE
exclude "Y" chromosome from bsseq object

### ISSUE THREAD

**Issue by demis001** [hansenlab/bsseq#129]
Please explain how to exclude the "Y" chromosome data from the "bsseq" object. I want to exclude the "Y" range data and coverage simultaneously.

Best,
Dereje Jima

**Comment by PeteHaitch** [comment]
If you're _BSseq_ object is called `bsseq`, then `bsseq[seqnames(bsseq) != "chrY", ]`or `bsseq[seqnames(bsseq) != "Y", ]`  will do it (depending on what the Y chromosome is named in your data).
General question like this are better posted to https://support.bioconductor.org/.

**Comment by demis001** [comment]
@PeteHaitch  I just registered to bioconductor.org, and the site couldn't allow me to create a new post. I want to bother you one more time. I initially filtered CpG loci with a median coverage of 4 or greater with 50% or less missing value among all participants. Would you please guide me on how to apply imputation to both "M" and "Cov" in the BSseq object?

**Comment by PeteHaitch** [comment]
I've never used imputation.
