### ISSUE TITLE
Upcoming change to DelayedArray::realize()

### ISSUE THREAD

**Issue by hpages** [hansenlab/bsseq#133]
See https://github.com/hansenlab/minfi/issues/256 for the details.

Like for **minfi**, I will try to come up with a PR for **bsseq** if I see that the change breaks it.

Cheers,
H.

**Comment by hpages** [comment]
Looks like this change didn't cause any problem: https://bioconductor.org/checkResults/3.19/bioc-LATEST/bsseq/

Closing this now.

**Comment by PeteHaitch** [comment]
Thanks, Hervé.
