### ISSUE TITLE
geneTrack in plotRegion

### ISSUE THREAD

**Issue by RicardoMartins-Ferreira** [hansenlab/bsseq#139]
Greetings,

I am trying to add geneTrack to the plotRegion function. In the user's guide, it says that it should be a data.frame with columns: chr, start, end, gene_ID,exon_number, strand, gene_name, isoforms. 
I tried to create a table of such from the https://genome.ucsc.edu/ Table Browser.
My geneTrack looks like the following:

![image](https://github.com/user-attachments/assets/b2e0619a-3685-4059-9c60-3d5bdc01e164)

Running the plotManyRegions function, I get the following warning and no geneTrack is plotted:
plotManyRegions(bsseq.fit, dmrs[1:2,], extend = 5000,
+                 addRegions = dmrs,geneTrack = geneTrack)
[plotManyRegions] preprocessing ...done
[plotManyRegions]   plotting region 1 (out of 2)

Warning in .merge_two_Seqinfo_objects(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)

Could you please guide me on what the geneTrack data table should look like?

Best,

Ricardo Martins-Ferreira

**Comment by PeteHaitch** [comment]
Are you able to share a subset of your data that reproduces the error so I can take a closer look?

**Comment by RicardoMartins-Ferreira** [comment]
Thank you for the reply.
Please find attached a subset of the dmrs file and the genetrack file.
[dmrs_example.txt](https://github.com/user-attachments/files/16493426/dmrs_example.txt)
[genetrack.txt](https://github.com/user-attachments/files/16493427/genetrack.txt)

**Comment by PeteHaitch** [comment]
Can you please also share a subset of the `bsseq.fit` _BSseq_ object that is sufficient to reproduce the error.

**Comment by RicardoMartins-Ferreira** [comment]
[bsseq_fit_subset.zip](https://github.com/user-attachments/files/16511006/bsseq_fit_subset.zip)
There you go. This corresponds to the bsseq.fit object filtered to include only chrUn_GL456396, which includes the two first dmrs.

Thanks!

**Comment by PeteHaitch** [comment]
Your `dmrs` and `geneTrack` objects have no common seqlevels (chromosomes), as shown in this code chunk:

```r
suppressPackageStartupMessages(library(bsseq))
suppressPackageStartupMessages(library(here))

dmrs <- read.table("data/dmrs_example.txt")
geneTrack <- read.table("data/genetrack.txt")

dmrs_gr <- as(dmrs, "GRanges")
geneTrack_gr <- as(geneTrack, "GRanges")
# There is no overlap of the `dmrs` and `geneTrack`, they don't even have
# common seqlevels.
#> intersect(dmrs_gr, geneTrack_gr)
#> GRanges object with 0 ranges and 0 metadata columns:
#>    seqnames    ranges strand
#>       <Rle> <IRanges>  <Rle>
#>   -------
#>   seqinfo: 9 sequences from an unspecified genome; no seqlengths
#> Warning message:
#> In .merge_two_Seqinfo_objects(x, y) :
#>   The 2 combined objects have no sequence levels in common. (Use
#>   suppressWarnings() to suppress this warning.)
seqlevels(dmrs_gr)
#> [1] "chr7"           "chrUn_GL456389" "chrUn_GL456390" "chrUn_GL456392" "chrUn_GL456396"
seqlevels(geneTrack_gr)
#> [1] "chr1" "chr2" "chr3" "chr4"
```

You'll see the same warning in the above example as what you are seeing when you run `plotManyRegions()` with these data.
`plotManyRegions()` will only plot genes that are in the same window as the data you are plotting, so you need to provide a `geneTrack` that includes any genes in the regions you are plotting.

**Comment by RicardoMartins-Ferreira** [comment]
Thank you very much for your response. Would you have any reference geneTracks file to be used or suggestions to develop one?

Best.

**Comment by PeteHaitch** [comment]
I'm afraid I don't think we have many public examples of creating a gene track for plotting.
I did find one from 6 years ago - https://github.com/hansenlab/BrainEpigenomeNN/blob/master/nonCG/objects/RefSeq_exons3.rds - which you might be able to look at to reverse engineer the required format.
