### ISSUE TITLE
DMCs and DMRs of large numbers of biological replicates

### ISSUE THREAD

**Issue by CTLife** [hansenlab/bsseq#67]
BSseq, is it appropriate for RRBS data with large numbers of biological replicates ?     
Such as 100 biological replicates of each group for detecting DMCs and DMRs.        
Or which method should I choose for large numbers of biological replicates ?

**Comment by PeteHaitch** [comment]
This question is better directed to http://support.bioconductor.org/. 

I don't believe we have used BSseq to analyse RRBS data. The first problem that comes to mind is how to meaningfully smooth RRBS data.
