### ISSUE TITLE
How to use bsseq to find differentially methylated promoter?

### ISSUE THREAD

**Issue by LinXialab** [hansenlab/bsseq#73]
Hi, I learned that bsseq can be used to find DMR in specific regions, like promoter. I wonder that where can I find the protocol about how to use bsseq find differentially methylated promoter.

**Comment by PeteHaitch** [comment]
HI @LinXialab,

General questions like this are perhaps better posted to the Bioconductor support forum (http://support.bioconductor.org/). 
There's nothing specific in **bsseq** for finding DMRs at pre-annotated regions. You'll need to decide how to summarise methylation at your regions (perhaps accounting/weighting for variable CpG density), and then run a regression for your covariate(s) of interest. @kasperdanielhansen may have more to say.

**Comment by LinXialab** [comment]
Hi @PeteHaitch ,

I'm glad to get your timely answer, it's really helpfully.
But could you please tell me more detail?
Could you please told us how do the variable CpG density affect the methylation of regions?
How can we account/weight our covariate(s) of interest when use bsseq?

Best wishes!

**Comment by PeteHaitch** [comment]
I'm sorry, this is a research question, not something that can be answered in a brief github comment.
