### ISSUE TITLE
read.bismark performance?

### ISSUE THREAD

**Issue by jagi25** [hansenlab/bsseq#82]
There is an issue regarding the performance of the read.bismark argument (bsseq package 1.18.0). Tried to run this code for 48 samples and it keeps running now for over 24 hours on a high performance server without replying an error. However with an older version (1.14.0) it just took maximum 1 hour, but i need to use to newest right now. 

Files were provided in the .cov.gz format (files_met) and for colData a necessary dataframe with rownames (sample.names_df). 

Code:

```R
> bismarkBSseq <- read.bismark(files_met, loci=NULL, colData=sample.names_df, rmZeroCov = T, nThread=12, strandCollapse = F, verbose = T)
[read.bismark] Parsing files and constructing valid loci ...
Done in 236.2 secs
[read.bismark] Parsing files and constructing 'M' and 'Cov' matrices ...
```

R version (3.5.3)

Hope you can help me?

**Comment by PeteHaitch** [comment]
Are you able to narrow down the number of files it works for?
Perhaps try 1, 2, 4, 8, 16, 24, 48 files (and then a binary search to further narrow it down if necessary).
Could you also please try setting `verbose = 2`, which will give you more verbose output that may help in debugging.
Also, please try explicitly setting `BPPARAM` as `BPPARAM = BiocParallel::SerialParam()` to ensure it's not unintentionally using additional parallelisation on top of that specified by `nThread = 12`.
You might also set `BPPARAM = BiocParallel::SerialParam(progressbar = TRUE)` to track the progress.

**Comment by zyqfrog10** [comment]
**BPPARAM = BiocParallel::SerialParam()** is necessary for the combination of R 3.6, bsseq 1.22.0, and BiocParallel 1.20.0 too, even for two samples only. 
Thanks, PeteHaitch.

**Comment by PeteHaitch** [comment]
Can you please provide a reproducible example?

**Comment by demis001** [comment]
I am reading in 52 samples; it is extremely slow.  I have 100 processors.  It reads one file very fast; when I pass a vector of 52 samples, reading the first one takes too long. Any idea?

bs.black <- read.bismark(files = file_names_black,
                             colData = DataFrame(short_names_black),
                             rmZeroCov = F,
                             strandCollapse = TRUE,
                             BACKEND = "HDF5Array",
                             nThread = 52,
                             BPPARAM =  BiocParallel::SerialParam(),
                             verbose = 2)
bs.black

**Comment by PeteHaitch** [comment]
With that invocation, `read.bismark()` has to first parse all 52 files to obtain the union of genomic loci.
If you know in advance what these loci are, then you can provide them as a _GRanges_ object via the `loci` agument and it will not have to do that step.
Please read the documentation for further advice and if you are still having problems please open a new issue rather than posting to a years' old one.
